-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- Big list of names to choose from for node names in GT-Wumpus
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

NODE_NAMES_DICTIONARY = {
   "Epora",
   "Randas",
   "Motari",
   "Terrakk",
   "Angless",
   "Besser",
   "Gregas",
   "Frazen",
   "Zethras",
   "Ammonas",
   "rynion",
   "Oil Slip Industries",
   "Tick Tock Factories",
   "Rabbit Run Services",
   "Bubble-Gum Dam Solutions",
   "Coolant-Aid",
   "Mr. Obvious's Conundrums",
   "The Tip-Top Plains",
   "Valewood Forrest",
   "Forest Fairy's Berries",
   "Apple Mountain",
   "Turbo's Shack",
   "Fountain of Chocolate",
   "Fountain of Mustard",
   "The Giant Greenwood Tree",
   "Redwood Acres",
   "Tanuki Farm",
   "Hundred Acre Wood",
   "Thousand Acre Wood",
   "Ten-Thousand Acre Wood",
   "Chain links R' Us",
   "Doc Gabe's Medicine",
   "Drama Asylum",
   "Drastic's Relaxic",
   "Advisors R' Us",
   "Games Annonymous",
   "Furlock Gomes",
   "Wingle & Dingle & Hingle Lawfirm",
   "Cash Shop City",
   "Garges Pet Shop",
   "Gorilla Massages",
   "Wistick's Produce",
   "Apanda's Massage Parlour",
   "Nizbit's Strip Joint",
   "Wicks Bar and Grill",
   "Fountain of Schnapps",
   "Prima's Guides to the City",
   "Angels of Death, Establishment #42",
   "Neffy's Platypus Shelter",
   "Moomoo's Rabbit Hutch",
   "Vince's Body Guard Outlet",
   "The Reilly and Lily Factor",
   "Sweets and Peeps",
   "Second National Bank of Madrigal",
   "Jamal's Hair Salon",
   "The Triple-C Colosseum",
   "Dalek Exterminator Service",
   "The Golden H Restaurant",
   "Cybermen Upgrade Specialists",
   "Camelot Amusement Park",
   "The Crystal Palace",
   "Weeping Angel's Eyewear",
   "Silurian's Drilling",
   "Hancock's Forgery",
   "Mutant Ninja Turtle's Karate Dojo",
   "The Antidisestablishment",
   "The Place to Be",
   "Reynold's Foileries",
   "Sesame Street",
   "Gang Tattoo Parlor",
   "Rosewood's Florist",
   "Meg and Ryan's Wedding Planning",
   "Aquaduct Air Conditioning",
   "Mister T's Corner",
   "Ye Olde Hobby Shop",
   "The Rich and Poor's Shop",
   "Sparkle's Pet Shop",
   "Fruits and Spirits",
   "Blum's Funeral Parlor",
   "Mark and Mort's Hockey Apparel"
};
